### ISSUE TITLE
Incorrect README instructions?

### ISSUE THREAD

**Issue by spilth** [eonist/ResourceHelper#1]
I gave this package a try today and had to do two things differently than outlined in the README:

## Dependency Declaration

I had to add the dependency as follows:

```
.package(
    url: "https://github.com/eonist/ResourceHelper.git",
    .branch("master")
)
```

The syntax is a little off in the README

## Usage Example

I had to do the following to use the package in my test:

```
import XCTest
import ResourceHelper
@testable import SongPro

final class SongProTests: XCTestCase {
    func testItParsesWholeSongs() throws {
        let path = ResourceHelper.projectRootURL(projectRef: #file, fileName: "bad-moon-rising.sng").path
        let bmr = try String(contentsOfFile: path)
        // ....
    }
}
```

It's `ResourceHelper`, not `ResourceUtil`.

**Comment by eonist** [comment]
Fixed. Thanks. 💚 Did it work? I use this lib everyday in my different repositories. I wonder if apple added this functionality natively now though. Any thoughts? Personally I haven't looked into apples solution but I think its something like this: https://medium.com/better-programming/how-to-add-resources-in-swift-package-manager-c437d44ec593

**Comment by spilth** [comment]
Yes, it worked! So thank you for making it. I'm only just getting started with Swift and SwiftUI, so I'm currently on Swift 5.2 and your package gets the job done.

If you're curious: https://github.com/SongProOrg/songpro-swift

**Comment by eonist** [comment]
SongPro looks really sweet. lots of exciting opportunities in the audio field these days 💪
